server:
  port: 8456
logging:
  file: /java/C2S_LOGS/c2s-ui/c2s-ui.log
info:
  component: C2S UI
---
# enables ssl and adds /c2s-ui context path when activated
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /c2s-ui